---
title: "Lab 4"
author: "Marijn Jaarsma"
date: "2024-10-09"
output: html_document
---

```{r}
library(kernlab)
```

# Question 2.1.1
```{r}
posteriorGP <- function(X, y, XStar, sigmaNoise, k) {
  res <- list()
  
  # Compute covariance and Cholesky decomposition
  K <- k(X, X)
  L <- t(chol(K + sigmaNoise * diag(dim(K)[1])))
  
  # Compute predictive mean
  k_star <- k(X, XStar)
  alpha <- solve(t(L), solve(L, y))
  res$pred_mean <- t(k_star) %*% alpha
  
  # Compute predictive variance
  v <- solve(L, k_star)
  res$pred_var <- k(XStar, XStar) - t(v) %*% v
  
  # Compute log marginal likelihood
  n <- length(y)
  res$log_marg_lik <- -0.5 * t(y) %*% alpha - sum(log(diag(L)) - n/2 * log(2 * pi))

  return(res)
}
```

# Question 2.1.2
```{r}
# Hyperparameters
sigmaF_hyp <- 1
l_hyp <- 0.3

# Covariance function
SquaredExpKernel <- function(x1, x2, sigmaF=sigmaF_hyp, l=l_hyp){
  n1 <- length(x1)
  n2 <- length(x2)
  K <- matrix(NA,n1,n2)
  for (i in 1:n2){
    K[,i] <- sigmaF^2*exp(-0.5*( (x1-x2[i])/l)^2 )
  }
  return(K)
}

# Assumptions and data
sigmaNoise <- 0.1
X <- 0.4
y <- 0.719

X_grid <- seq(-1, 1, length.out=100)
means <- c()
vars <- c()
for (XStar in X_grid) {
  res <- posteriorGP(X, y, XStar, sigmaNoise, SquaredExpKernel)  
  means <- append(means, res$pred_mean)
  vars <- append(vars, res$pred_var)
}

# Plot means with 95% CI
plot(X_grid, means, type="l", ylim=c(-2, 2), main="Posterior with 1 data point")
lines(X_grid, means + 1.96 * sqrt(vars), col="blue")
lines(X_grid, means - 1.96 * sqrt(vars), col="blue")
```

# Question 2.1.3
```{r}
X <- append(X, -0.6)
y <- append(y, -0.044)

means <- c()
vars <- c()
for (XStar in X_grid) {
  res <- posteriorGP(X, y, XStar, sigmaNoise, SquaredExpKernel)  
  means <- append(means, res$pred_mean)
  vars <- append(vars, res$pred_var)
}

# Plot means with 95% CI
plot(X_grid, means, type="l", ylim=c(-2, 2), main="Posterior with 2 data points")
lines(X_grid, means + 1.96 * sqrt(vars), col="blue")
lines(X_grid, means - 1.96 * sqrt(vars), col="blue")
```
# Question 2.1.4
```{r}
X <- c(-1, -0.6, -0.2, 0.4, 0.8)
y <- c(0.768, -0.044, -0.94, 0.719, -0.664)

means <- c()
vars <- c()
for (XStar in X_grid) {
  res <- posteriorGP(X, y, XStar, sigmaNoise, SquaredExpKernel)  
  means <- append(means, res$pred_mean)
  vars <- append(vars, res$pred_var)
}

# Plot means with 95% CI
plot(X_grid, means, type="l", ylim=c(-2, 2), main="Posterior with 2 data points")
lines(X_grid, means + 1.96 * sqrt(vars), col="blue")
lines(X_grid, means - 1.96 * sqrt(vars), col="blue")
```

# Question 2.1.5
```{r}
sigmaF_hyp <- l_hyp <- 1

X <- c(-1, -0.6, -0.2, 0.4, 0.8)
y <- c(0.768, -0.044, -0.94, 0.719, -0.664)

means <- c()
vars <- c()
for (XStar in X_grid) {
  res <- posteriorGP(X, y, XStar, sigmaNoise, SquaredExpKernel)  
  means <- append(means, res$pred_mean)
  vars <- append(vars, res$pred_var)
}

# Plot means with 95% CI
plot(X_grid, means, type="l", ylim=c(-2, 2), main="Posterior with 2 data points")
lines(X_grid, means + 1.96 * sqrt(vars), col="blue")
lines(X_grid, means - 1.96 * sqrt(vars), col="blue")
```

# 2.2.1
```{r}
# Read data
df <- read.csv("https://github.com/STIMALiU/AdvMLCourse/raw/master/GaussianProcess/Code/TempTullinge.csv", header=TRUE, sep=";")

# Convert string date column to date type
df["date"] <- lapply(df["date"], strptime, format=date_format, tz="UTC") # UTC to ignore Daylight Savings Time differences
df["time"] <- lapply(df["date"], difftime, time2=df[1, "date"], units="days")
df$time <- as.numeric(df$time)
# Define kernel
square_exponential_kernel <- function(x1, x2, ell=ell_hyp, sigmaf=sigmaf_hyp) {
  return (sigmaf ** 2 * exp(-sqrt(sum((x1 - x2) ** 2)) ** 2 / (2 * ell ** 2)))
}
class(square_exponential_kernel) <- "kernel"

# Define data and set random hyper parameters and run kernel
X <- c(1, 3, 4)
X_star <- c(2, 3, 4)
ell_hyp <- 0.3
sigmaf_hyp <- 1

kernelMatrix(square_exponential_kernel, X, X_star)
```

# 2.2.2
```{r}
lin_mod <- lm("temp ~ time", df)
sigma_n_2 <- var(lin_mod$residuals)

ell_hyp <- 100
sigmaf_hyp <- 20

mod <- gausspr(df["time"], df["temp"], kernel=square_exponential_kernel, kpar=list(ell_hyp, sigmaf_hyp), scaled=FALSE)

```